/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

import backEnd.ArvoreBinaria;
import backEnd.HeapBinaria;
import backEnd.Participante;
import backEnd.ProjetoFinalLEDA;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

public class telaQtdJogadores extends javax.swing.JFrame {

    /**
     * Creates new form telaJogador
     */
    public telaQtdJogadores() {
        initComponents();
        telaVazia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComeçar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmpJogador1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmpJogador2 = new javax.swing.JTextField();
        cmpJogador3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmpJogador4 = new javax.swing.JTextField();
        vipPlayer1 = new javax.swing.JCheckBox();
        vipPlayer2 = new javax.swing.JCheckBox();
        vipPlayer3 = new javax.swing.JCheckBox();
        vipPlayer4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        qtdJogadores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        btnComeçar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnComeçar.setForeground(new java.awt.Color(51, 51, 51));
        btnComeçar.setText("Começar");
        btnComeçar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComeçarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComeçar);
        btnComeçar.setBounds(230, 430, 335, 49);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Jogador 1");

        cmpJogador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Jogador 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Jogador 3");

        cmpJogador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmpJogador3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Jogador 4");

        cmpJogador4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vipPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        vipPlayer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vipPlayer1.setForeground(new java.awt.Color(51, 51, 51));
        vipPlayer1.setText("Premium");
        vipPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipPlayer1ActionPerformed(evt);
            }
        });

        vipPlayer2.setBackground(new java.awt.Color(255, 255, 255));
        vipPlayer2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vipPlayer2.setForeground(new java.awt.Color(51, 51, 51));
        vipPlayer2.setText("Premium");
        vipPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipPlayer2ActionPerformed(evt);
            }
        });

        vipPlayer3.setBackground(new java.awt.Color(255, 255, 255));
        vipPlayer3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vipPlayer3.setForeground(new java.awt.Color(51, 51, 51));
        vipPlayer3.setText("Premium");

        vipPlayer4.setBackground(new java.awt.Color(255, 255, 255));
        vipPlayer4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vipPlayer4.setForeground(new java.awt.Color(51, 51, 51));
        vipPlayer4.setText("Premium");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmpJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(cmpJogador2)
                    .addComponent(cmpJogador3)
                    .addComponent(cmpJogador4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(vipPlayer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vipPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vipPlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vipPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vipPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vipPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vipPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(vipPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 250, 360, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\team.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 60, 130, 110);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        qtdJogadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtdJogadores.setForeground(new java.awt.Color(51, 51, 51));
        qtdJogadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        qtdJogadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                qtdJogadoresItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Escolha a quantidade de jogadores:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(402, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void telaVazia() {
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        cmpJogador1.setVisible(false);
        cmpJogador2.setVisible(false);
        cmpJogador3.setVisible(false);
        cmpJogador4.setVisible(false);
        vipPlayer1.setVisible(false);
        vipPlayer2.setVisible(false);
        vipPlayer3.setVisible(false);
        vipPlayer4.setVisible(false);
    }

    public void umJogador() {
        jLabel2.setVisible(true);
        cmpJogador1.setVisible(true);
        jLabel3.setVisible(false);
        cmpJogador2.setVisible(false);
        jLabel4.setVisible(false);
        cmpJogador3.setVisible(false);
        jLabel5.setVisible(false);
        cmpJogador4.setVisible(false);
        vipPlayer1.setVisible(true);
        vipPlayer2.setVisible(false);
        vipPlayer3.setVisible(false);
        vipPlayer4.setVisible(false);
    }

    public void doisJogadores() {
        jLabel2.setVisible(true);
        cmpJogador1.setVisible(true);
        jLabel3.setVisible(true);
        cmpJogador2.setVisible(true);
        jLabel4.setVisible(false);
        cmpJogador3.setVisible(false);
        jLabel5.setVisible(false);
        cmpJogador4.setVisible(false);
        vipPlayer1.setVisible(true);
        vipPlayer2.setVisible(true);
        vipPlayer3.setVisible(false);
        vipPlayer4.setVisible(false);
    }

    public void tresJogadores() {
        jLabel2.setVisible(true);
        cmpJogador1.setVisible(true);
        jLabel3.setVisible(true);
        cmpJogador2.setVisible(true);
        jLabel4.setVisible(true);
        cmpJogador3.setVisible(true);
        jLabel5.setVisible(false);
        cmpJogador4.setVisible(false);
        vipPlayer1.setVisible(true);
        vipPlayer2.setVisible(true);
        vipPlayer3.setVisible(true);
        vipPlayer4.setVisible(false);
    }

    public void quatroJogadores() {
        jLabel2.setVisible(true);
        cmpJogador1.setVisible(true);
        jLabel3.setVisible(true);
        cmpJogador2.setVisible(true);
        jLabel4.setVisible(true);
        cmpJogador3.setVisible(true);
        jLabel5.setVisible(true);
        cmpJogador4.setVisible(true);
        vipPlayer1.setVisible(true);
        vipPlayer2.setVisible(true);
        vipPlayer3.setVisible(true);
        vipPlayer4.setVisible(true);
    }

    public ArvoreBinaria escolherArvore(ArvoreBinaria av1, ArvoreBinaria av2, ArvoreBinaria av3, ArvoreBinaria av4) {
        Random rd = new Random();
        int rand = rd.nextInt(3);
        ArvoreBinaria avEscolhida = null;
        switch (rand) {
            case 0:
                avEscolhida = av1;
                break;
            case 1:
                avEscolhida = av2;
                break;
            case 2:
                avEscolhida = av3;
                break;
            case 3:
                avEscolhida = av4;
                break;
            default:
        }
        return avEscolhida;
    }

    private void qtdJogadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_qtdJogadoresItemStateChanged
        int quantidade = qtdJogadores.getSelectedIndex();

        switch (quantidade) {
            case 1:
                umJogador();
                break;
            case 2:
                doisJogadores();
                break;
            case 3:
                tresJogadores();
                break;
            case 4:
                quatroJogadores();
                break;
            default:

        }

    }//GEN-LAST:event_qtdJogadoresItemStateChanged

    private void btnComeçarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComeçarActionPerformed
        dispose();

        String jogador1 = cmpJogador1.getText();
        boolean vip1 = vipPlayer1.isSelected();
        String jogador2 = cmpJogador2.getText();
        boolean vip2 = vipPlayer2.isSelected();
        String jogador3 = cmpJogador3.getText();
        boolean vip3 = vipPlayer3.isSelected();
        String jogador4 = cmpJogador4.getText();
        boolean vip4 = vipPlayer4.isSelected();

        int qtdjogadores = qtdJogadores.getSelectedIndex();

        //preenche as arvores
        ProjetoFinalLEDA pj = new ProjetoFinalLEDA();
        ArvoreBinaria av1 = pj.transporte();
        ArvoreBinaria av2 = pj.alimento();
        ArvoreBinaria av3 = pj.animal();
        ArvoreBinaria av4 = pj.profissao();

        ArrayList<Participante> fila = new ArrayList();

        switch (qtdjogadores) {
            case 1:
                fila.add(new Participante(jogador1, vip1));
                break;
            case 2:
                fila.add(new Participante(jogador1, vip1));
                fila.add(new Participante(jogador2, vip2));
                break;
            case 3:
                fila.add(new Participante(jogador1, vip1));
                fila.add(new Participante(jogador2, vip2));
                fila.add(new Participante(jogador3, vip3));
                break;
            case 4:
                fila.add(new Participante(jogador1, vip1));
                fila.add(new Participante(jogador2, vip2));
                fila.add(new Participante(jogador3, vip3));
                fila.add(new Participante(jogador4, vip4));
                break;
            default:
        }

        HeapBinaria heap = new HeapBinaria();
        heap.buildHeap(fila);

        ArvoreBinaria[] arvores = new ArvoreBinaria[4];
        arvores[0] = av1;
        arvores[1] = av2;
        arvores[2] = av3;
        arvores[3] = av4;

        telaJogador view = new telaJogador(fila, arvores);
        view.setInfos();

        view.setVisible(true);

        /*mostra dicas e resposta do caminho

        String[] dicas = new String[5];

        String d = escolherArvore(av1, av2, av3, av4).caminhoAleatorio(dicas);

        for (int i = 0; i < dicas.length; i++) {
            System.out.println(dicas[i]);
        }
        System.out.println(d);
         */
    }//GEN-LAST:event_btnComeçarActionPerformed

    private void vipPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vipPlayer1ActionPerformed

    private void vipPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vipPlayer2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComeçar;
    private javax.swing.JTextField cmpJogador1;
    private javax.swing.JTextField cmpJogador2;
    private javax.swing.JTextField cmpJogador3;
    private javax.swing.JTextField cmpJogador4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> qtdJogadores;
    private javax.swing.JCheckBox vipPlayer1;
    private javax.swing.JCheckBox vipPlayer2;
    private javax.swing.JCheckBox vipPlayer3;
    private javax.swing.JCheckBox vipPlayer4;
    // End of variables declaration//GEN-END:variables
}
